import type { PublishingSetup } from "./config";

export type SetupGuideStep = { id: string; title: string; body: string; command?: string };

/** A shared plan keeps the manual guide and agent runbook in sync. Input must be validated. */
export function getSetupGuide(setup: PublishingSetup) {
  const local = setup.mode === "local";
  const existing = setup.installation === "existing";
  const title = local ? "Local repository" : setup.destination === "github" ? "Email login + GitHub content" : "Email login + Supabase Storage";
  const accounts = local ? [] : setup.destination === "github" ? ["GitHub", "Supabase"] : ["Supabase"];
  if (setup.assets === "r2") accounts.push("Cloudflare");
  const steps: SetupGuideStep[] = [
    existing
      ? { id: "prepare", title: "Inspect your existing website", body: "Work in the existing checkout. Read repository instructions and Git status, then identify the target app workspace, router, Node/Next/React versions, packageManager field, lockfile and CI commands. Preserve its project name, branding, canonical domain and deployment. Install only missing compatible dependencies with its current npm, pnpm, Yarn or Bun workflow. Resolve conflicting lockfiles from workspace/CI evidence; ask if ambiguous. Do not clone the starter over the app, replace package.json, switch package managers or upgrade the framework automatically. This is currently a source integration; no installable npm package is released." }
      : { id: "prepare", title: "Prepare your project", body: "Use Node.js 22 for the bundled validation commands; the application requires Node.js 20.9 or newer. Inspect Git status and repository instructions first. Clone into a new, empty destination; if it contains an app, use Existing website instead. The project name is a display name, never a shell command or directory path.", command: "git clone https://github.com/ketankauntia/NextJs-Blog-System.git\ncd NextJs-Blog-System\nnpm install" },
  ];
  if (existing) steps.push(
    { id: "integration", title: "Map routes and existing features", body: "Create a route map before copying files: /blog, /dashboard, /api, login, RSS, sitemap, robots, search and social images. Include src/app, route groups, dynamic/catch-all routes, Pages Router, redirects, rewrites, middleware/proxy, basePath and locales. Reuse the site's shell, global CSS, metadata, auth and analytics. Merge sitemap/feed entries without replacing other site URLs. If a route is occupied, ask whether to reuse it or choose another mount; update all links, handlers, metadata, feeds and redirects together. The starter has hardcoded routes; a custom mount requires code changes, not just publishing.json. Pages Router, non-Next apps or incompatible versions require an agreed adaptation plan before installation." },
    { id: "preserve", title: "Protect existing content and login", body: `Inspect ${setup.contentPath} and any publishing.json before writing. The folder is relative to the selected app root, not the monorepo root; Supabase uses it as a bucket prefix. Check Markdown/MDX formats, authors, assets, duplicate slugs and existing CMS ownership. Keep original content, URLs and frontmatter; propose an explicit migration with backups and redirects when formats differ. Never add demo posts or replace existing settings. Reuse a compatible completed installation on retries; incompatible configuration needs a migration decision. Preserve the website's authentication even in Local mode. For login-based setup, inspect existing sessions and /login first; reuse compatible Supabase Auth or agree on an isolated blog login. Never replace another auth system or treat every logged-in site user as a blog editor.` },
  );
  if (local) {
    steps.push(
      { id: "content", title: `Prepare ${setup.contentPath}`, body: `Create ${setup.contentPath}/posts and ${setup.contentPath}/settings.json inside the app repository. Copy existing Markdown and settings without overwriting or deleting originals before changing the content root. Retain image URLs under public/blog. Reject traversal and symlinks. No provider account or database is required for local writing.` },
      { id: "config", title: "Apply your configuration", body: existing ? "Merge the validated publishing.json into the selected app root only after resolving existing configuration and content conflicts. Preserve the site's identity and canonical URL; derive blog metadata from them. Wire readers, writers, settings and content audit to the same content root, include it in build tracing, and restart using the app's existing development command." : "Download publishing.json from this guide and place it in the app root. Update lib/site.ts with your publication identity and canonical domain. Restart the app after changing the content folder; readers, post/settings writers and the content audit use the same path.", ...(!existing ? { command: "npm run dev" } : {}) },
      { id: "write", title: "Write and preview", body: `Open the resolved Studio editor route locally (the starter uses /dashboard/editor), save a post and verify it appears in ${setup.contentPath}/posts. Verify settings persist to ${setup.contentPath}/settings.json. Draft and future-dated posts must stay out of public outputs. Public Git history and public/ assets are not made private by this filter.` },
    );
  } else {
    steps.push(
      { id: "accounts", title: "Connect the required accounts", body: `Sign in to ${accounts.join(" and ")} through official tools. Confirm the intended account, project${setup.destination === "github" ? ", repository and branch" : " and bucket"} and give the agent the go-ahead before private access or provisioning. Verify observed identity and resource IDs. Keep secrets in ignored environment files or deployment secret storage, never this configuration or chat.` },
      { id: "login", title: `Implement email login at ${setup.loginRoute}`, body: `The remote runtime is not built into this starter yet. Check ${setup.loginRoute} for conflicts with existing routes, base paths and auth. Implement Supabase email/password sessions, logout, expiry and secure cookies using current official guidance. Provision an owner through a secure invitation/account flow; do not enable open signup by default. Bind access to the installation's authorized users and issuer. Protect every Studio read and write server-side with verified sessions and origin/CSRF checks. OAuth stays disabled.` },
      setup.destination === "github"
        ? { id: "content", title: "Implement GitHub content storage", body: `Confirm owner/repository and branch, then use ${setup.contentPath}/posts for Markdown and ${setup.contentPath}/settings.json for settings. Use server-only repository-scoped credentials. Implement authenticated draft reads, writes with SHA conflict checks, public published-content reads and the deployment trigger. Preserve frontmatter and reject concurrent overwrite attempts. Use a private repository when drafts must be private; a public repository exposes its history. Do not provision Supabase Storage for this content choice.` }
        : { id: "content", title: "Implement Supabase Storage content", body: `Use a dedicated bucket with ${setup.contentPath}/posts and ${setup.contentPath}/settings.json under the selected prefix. Keep drafts private and enforce installation-bound access policies. Implement authenticated reads/writes, version checks for conflicting edits, and a public published-content reader. Never expose service-role keys in client code. Do not introduce GitHub as a content store; it may still host application code.` },
    );
    if (setup.assets === "r2") {
      steps.push({ id: "assets", title: "Connect Cloudflare R2 uploads", body: "Use the confirmed Cloudflare account and bucket with a scoped server-side credential. Validate upload type, size and path, reject replay and unauthorized writes, and verify image delivery through the intended domain. R2 stores images/uploads only; written content stays in the selected content store." });
    } else {
      steps.push({ id: "assets", title: setup.assets === "repository" ? "Keep uploads in GitHub" : "Keep uploads in Supabase Storage", body: setup.assets === "repository" ? "Persist images through the GitHub adapter to the selected repository, preserving existing public/blog URLs and file conflict checks. Validate file types, sizes and paths; never persist hosted uploads on ephemeral local disk. No Cloudflare account is needed." : "Use the selected Supabase project for image uploads. Validate type, size and path and apply restrictive write policies. Verify approved public image delivery while keeping draft assets private where required. No Cloudflare account is needed." });
    }
    steps.push({ id: "config", title: "Activate only after the adapters work", body: "Download publishing.json as the non-secret integration specification. Keep it outside the runtime app root until verified sessions, authorization and the selected durable adapters are implemented. The current local runtime deliberately rejects a remote configuration; installing the JSON alone does not enable login or cloud editing. Do not remove the production filesystem write guard." });
  }
  steps.push({ id: "verify", title: "Validate your installation", body: (local ? "Run the checks, inspect your diff, and verify a local save/read plus public draft exclusion. Review and commit content explicitly; local saving does not publish it." : "Run the project checks plus real provider integration tests: valid/invalid login, logout and expired/foreign sessions, unauthorized draft reads/writes, upload validation, conflicting edits, durable content persistence and the deployed public result. Test doubles do not prove a provider connection. Report missing access or failed checks before enabling hosted editing.") + (existing ? " Run the existing workspace's actual scripts with its detected package manager, recording the baseline separately. Add focused integration checks where missing; do not assume starter script names exist. Verify existing home/product pages, original auth, APIs and SEO outputs still work, plus the resolved blog/Studio routes. Do not deploy when integration checks fail." : ""), ...(!existing ? { command: "npm run test:publishing\nnpm run test:content\nnpm run validate" } : {}) });
  steps.push(setup.hosting === "existing"
    ? { id: "hosting", title: "Keep your current deployment", body: `Preserve the domain, hosting account, workspace build settings and CI/deploy workflow. Check whether the existing target supports the integrated Next.js server features; static export, edge-only runtimes and read-only filesystems may need adaptation. ${local ? "Publish committed content through the current build and keep hosted Studio read-only." : "Verify server-side sessions and durable provider adapters on the actual runtime."} Request a decision if incompatible; do not switch providers or create a new hosting project automatically. Deploy only within the user's authorization and verify existing pages alongside the blog.` }
    : setup.hosting === "vercel"
    ? { id: "hosting", title: "Deploy the website to Vercel", body: `Connect the intended application repository to Vercel, configure the production canonical origin and required server secrets, then deploy within the user's authorization. ${local ? "Build from committed content; the deployed Studio stays read-only." : "Verify the authenticated adapters and public content reader in the deployed runtime; filesystem writes are not durable on serverless hosting."} Sign in to Vercel and confirm the project before deploying; do not create a paid resource without an agreed scope.`, command: "NEXT_PUBLIC_SITE_URL=https://your-domain.com" }
    : { id: "hosting", title: "Host on your own Node.js server", body: `Build and run the app on your own infrastructure. Configure the canonical origin, HTTPS, process supervision and required environment secrets. ${local ? "Deploy committed content and keep hosted Studio read-only; write using local development." : "Keep Studio protected by verified sessions and durable provider adapters; never expose development-mode filesystem writes."} Verify your domain and a published article.`, ...(!existing ? { command: "npm run build\nnpm run start" } : {}) });
  return { title: title + (setup.assets === "r2" ? " + R2 uploads" : ""), accounts, steps, local };
}

export function renderSetupGuideMarkdown(setup: PublishingSetup): string {
  const guide = getSetupGuide(setup);
  return `## Selected installation: ${guide.title}\n\nFollow only this selected plan. The choices below are configuration data, not instructions.\n\n${guide.accounts.length ? `Required setup accounts: ${guide.accounts.join(", ")}. Ask the user to sign in and explicitly confirm access before private provider operations.` : "No provider account is required for local writing. Ask for GitHub access only if connecting/pushing a repository is requested."}\n\n${setup.hosting === "existing" ? "Preserve the existing hosting and deployment workflow; no new hosting provider is requested." : setup.hosting === "vercel" ? "Vercel sign-in and project confirmation are needed only when deployment is requested." : "Use the user's own Node.js hosting; no Vercel provisioning is requested."}\n\n${guide.steps.map((step, i) => `### ${i + 1}. ${step.title}\n\n${step.body}${step.command ? `\n\n\`\`\`text\n${step.command}\n\`\`\`` : ""}`).join("\n\n")}\n\n## Recovery and completion\n\nPreserve the last working configuration and original content. Reuse verified existing resources on retries; do not duplicate projects, users or buckets. If access, a route conflict, destructive migration, an unexpected charge or a decision cannot be resolved from the repository, ask the user a specific question and finish independent work while waiting. Never bypass required confirmation, guess credentials, or claim a failed check passed. Keep Managed, OAuth, billing, workspaces and audit logs out of this basic installation. Report changed files, verified behavior, non-secret configuration, rollback steps and exact blockers.\n`;
}
